import Header from "@/components/layouts/Header";
import Navigation from "@/components/layouts/Navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }: LayoutProps<"/">) {
    return (
        <>
            <Header />
            <main className="w-full max-w-lg flex-1 mx-auto bg-white relative p-4">
                {children}
            </main>
            <Navigation />
        </>
    );
}
