import Header from "@/components/layouts/Header";
import Navigation from "@/components/layouts/Navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function KantongKuLayout({ children }: LayoutProps<"/">) {
    return (
        <main className="w-full max-w-md flex-1 mx-auto bg-white relative">
            <Header />
            {children}
            <Navigation />
        </main>
    );
}
